apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: grpc-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
      - name: grpc-client
        image: saldsfoias/grpc:helloword
        command: ["./greeter_client","-address","grpc-server:50051"]
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
