apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tool
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tool
    spec:
      containers:
      - name: tool
        image: akuber/grpc:helloworld
        command: ["tail","-f","/etc/hosts"]
